name: Release

on:
    push:
      tags: 
        - "^[0-9]+.[0-9]+.[0-9]+(-[a-z0-9]+)?$"
    workflow_dispatch:
      inputs:
         version:
          description: 'Desired version of the package (without prefixing with "v")'
          required: true
          type: string

jobs:
    build-pack:
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: ./src
        steps:
            - uses: actions/checkout@v4

            - name: Set version variable
              id: set_version
              run: |
                if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                  echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
                else
                  echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
                fi

            - name: Setup dotnet 9.x.x
              uses: actions/setup-dotnet@v4
              with: 
                dotnet-version: 9.x.x

            - name: restore
              run: dotnet restore

            - name: build
              run: dotnet build -c Release  --no-restore 

            - name: test
              run: dotnet test -c Release --no-build

            - name: pack
              run: dotnet pack -c Release ./JsonMigration/JsonMigration.csproj --no-build --output ./output -p:Version=${{ env.VERSION }}

            - name: publish artifact
              uses: actions/upload-artifact@v4
              with:
                name: package
                path: ./outputon
                retention-days: 7

    publish-internal:
        runs-on: ubuntu-latest
        needs: build-pack

        steps:
          - name: download artifact
            uses: actions/download-artifact@v2
            with:
              name: package
              path: ./output
        
          - name: Setup dotnet 9.x.x
            uses: actions/setup-dotnet@v4
            with: 
              dotnet-version: 9.x.x 
              source-url: https://nuget.pkg.github.com/garcipat/index.json
            env:
              NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

          - name: Push generated package to GitHub registry
            run: dotnet push ./output/*.nupkg --source https://nuget.pkg.github.com/garcipat/index.json --api-key ${GITHUB_TOKEN} --no-symbols --skip-duplicate
            env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          